[package]
name = "rust-aes-tbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dhat = "0.3.3"
memory-stats = "1.1.0"

[profile.release]
debug = 1

[features]
dhat-heap = []
